// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcV4NhDU-hlQuULDWfQFcR6DCnKP1UYkA',
    appId: '1:486068714741:web:ef3308025796e61aeed9bc',
    messagingSenderId: '486068714741',
    projectId: 'lush-1a59b',
    authDomain: 'lush-1a59b.firebaseapp.com',
    storageBucket: 'lush-1a59b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_wVk7l4vpjCOaCKhYSWdxYKu4qddaGn0',
    appId: '1:486068714741:android:4cc31206d367c781eed9bc',
    messagingSenderId: '486068714741',
    projectId: 'lush-1a59b',
    storageBucket: 'lush-1a59b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNe8uBH-sZgW9tZ-Q1m2am_puvlYQ70Mw',
    appId: '1:486068714741:ios:47d899e50434b81eeed9bc',
    messagingSenderId: '486068714741',
    projectId: 'lush-1a59b',
    storageBucket: 'lush-1a59b.appspot.com',
    iosBundleId: 'com.example.lushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNe8uBH-sZgW9tZ-Q1m2am_puvlYQ70Mw',
    appId: '1:486068714741:ios:47d899e50434b81eeed9bc',
    messagingSenderId: '486068714741',
    projectId: 'lush-1a59b',
    storageBucket: 'lush-1a59b.appspot.com',
    iosBundleId: 'com.example.lushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcV4NhDU-hlQuULDWfQFcR6DCnKP1UYkA',
    appId: '1:486068714741:web:27414b404cdd58b4eed9bc',
    messagingSenderId: '486068714741',
    projectId: 'lush-1a59b',
    authDomain: 'lush-1a59b.firebaseapp.com',
    storageBucket: 'lush-1a59b.appspot.com',
  );

}